export const GENRE_ALIASES: Record<string, string> = {
  "hip hop": "Hip-Hop",
  "hip-hop": "Hip-Hop",
  "hiphop": "Hip-Hop",
  "rap": "Rap",
  "pop rap": "Pop Rap",
  "melodic rap": "Melodic Rap",
  "emo rap": "Emo Rap",
  "cloud rap": "Cloud Rap",
  "gangsta rap": "Gangsta Rap",
  "gangster rap": "Gangsta Rap",
  "southern hip hop": "Southern Hip-Hop",
  "southern hip-hop": "Southern Hip-Hop",
  "east coast hip hop": "East Coast Hip-Hop",
  "west coast hip hop": "West Coast Hip-Hop",
  "alternative hip hop": "Alternative Hip-Hop",
  "underground hip hop": "Underground Hip-Hop",
  "horrorcore": "Horrorcore",

  "trap": "Trap",
  "trap rap": "Trap",
  "drill": "Drill",
  "chicago drill": "Drill",
  "uk drill": "UK Drill",
  "brooklyn drill": "Brooklyn Drill",

  "rnb": "R&B",
  "r&b": "R&B",
  "randb": "R&B",
  "rhythm and blues": "R&B",
  "alternative rnb": "Alternative R&B",
  "alternative r&b": "Alternative R&B",
  "alt r&b": "Alternative R&B",
  "trapsoul": "Trap Soul",
  "trap soul": "Trap Soul",
  "neo soul": "Neo Soul",
  "soul": "Soul",

  "pop": "Pop",
  "dance pop": "Dance-Pop",
  "electropop": "Electropop",
  "indie pop": "Indie Pop",
  "bedroom pop": "Bedroom Pop",
  "synthpop": "Synthpop",
  "dream pop": "Dream Pop",
  "k-pop": "K-Pop",
  "kpop": "K-Pop",
  "j-pop": "J-Pop",
  "jpop": "J-Pop",

  "rock": "Rock",
  "alternative rock": "Alternative Rock",
  "indie rock": "Indie Rock",
  "pop rock": "Pop Rock",
  "classic rock": "Classic Rock",
  "hard rock": "Hard Rock",
  "punk": "Punk",
  "pop punk": "Pop Punk",
  "metal": "Metal",
  "heavy metal": "Metal",

  "electronic": "Electronic",
  "electronica": "Electronic",
  "edm": "EDM",
  "house": "House",
  "deep house": "Deep House",
  "tech house": "Tech House",
  "progressive house": "Progressive House",
  "future bass": "Future Bass",
  "dubstep": "Dubstep",
  "drum and bass": "Drum & Bass",
  "drum & bass": "Drum & Bass",
  "dnb": "Drum & Bass",
  "techno": "Techno",
  "trance": "Trance",

  "afrobeats": "Afrobeats",
  "afrobeat": "Afrobeat",
  "amapiano": "Amapiano",
  "dancehall": "Dancehall",
  "reggae": "Reggae",
  "reggaeton": "Reggaeton",
  "latin": "Latin",
  "latin pop": "Latin Pop",

  "country": "Country",
  "folk": "Folk",
  "indie folk": "Indie Folk",
  "jazz": "Jazz",
  "jazz rap": "Jazz Rap",
  "blues": "Blues",
  "classical": "Classical",
  "soundtrack": "Soundtrack",
  "lo-fi": "Lo-Fi",
  "lofi": "Lo-Fi"
};

export const GENRE_PRIORITY: string[] = [
  "Drill",
  "UK Drill",
  "Brooklyn Drill",
  "Trap Soul",
  "Alternative R&B",
  "R&B",
  "Horrorcore",
  "Gangsta Rap",
  "Southern Hip-Hop",
  "Pop Rap",
  "Melodic Rap",
  "Emo Rap",
  "Cloud Rap",
  "Trap",
  "Rap",
  "Hip-Hop",
  "Dance-Pop",
  "Pop",
  "Rock",
  "Electronic"
];

export const JUNK_TAGS = new Set([
  "seen live",
  "favorites",
  "favourite",
  "favorite",
  "awesome",
  "good",
  "best",
  "love",
  "yeah",
  "spotify",
  "male vocalists",
  "female vocalists",
  "american",
  "canadian",
  "british",
  "usa",
  "canada",
  "chicago",
  "atlanta",
  "new york",
  "young money",
  "cash money",
  "ovo",
  "explicit"
]);
